import datetime
import json
import os
import re

import anthropic

with open(os.path.join(os.path.dirname(__file__), "prompts", "system_prompt.txt")) as _f:
    SYSTEM_PROMPT = _f.read().strip()


class InsufficientContentError(Exception):
    pass


def generate_cards(notes: str, api_key: str, model: str) -> list[dict]:
    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model=model,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": notes}],
    )
    text = message.content[0].text.strip()
    # Extract JSON (array or object) even if wrapped in markdown code fences
    match = re.search(r"(\[.*\]|\{.*\})", text, re.DOTALL)
    if match:
        text = match.group(0)
    parsed = json.loads(text)
    if isinstance(parsed, dict) and parsed.get("error") == "insufficient_content":
        raise InsufficientContentError
    return [{"front": c["front"], "back": c["back"] + f"\n\n(Auto-generated by {model})", "selected": True} for c in parsed]


def build_log(notes: str, model: str, cards: list[dict]) -> str:
    lines = [
        f"# Anki Flashcard Generator — Dev Log",
        f"Generated: {datetime.datetime.now().isoformat()}",
        f"Model: {model}",
        f"Cards generated: {len(cards)}",
        "",
        "## Input Notes",
        notes.strip(),
        "",
        "## Generated Flashcards",
    ]
    for i, c in enumerate(cards, 1):
        lines += [f"\n### Card {i}", f"**Front:** {c['front']}", f"**Back:** {c['back']}"]
    return "\n".join(lines)
